### ISSUE TITLE
Update nexus from online file

### ISSUE THREAD

**Issue by SimonGreenhill** [phlorest/grollemund_et_al2015#2]
and streamline the code.

http://www.evolution.rdg.ac.uk/DataSets.html

**Comment by xrotwang** [comment]
Should we just grab the Nexus from that download or still parse the excel sheet to built "our own" nexus?

**Comment by xrotwang** [comment]
If we want to just grab their Nexus, we'd have to reshuffle `etc/characters.csv`.

**Comment by xrotwang** [comment]
Notes to self:
```python
taxao - taxat
{'D305_Nyanga-li', 'D308_Bodo2', 'D20B_Vamba_1919', 'D308_Ebodo', 'D304_Homa_1919'}
taxat -taxao
{'*D304_Homa_1919', '*D305_Nyanga-li', '*D308_Bodo2', '*D308_Ebodo', '*D20B_Vamba_1919'}
```

**Comment by xrotwang** [comment]
Another note: "Their" Nexus has gaps (`-`) where "ours" has missing (`?`).

**Comment by xrotwang** [comment]
Once these two issues addressed, I get at least identical symbol counts for all taxa in the matrices.

**Comment by SimonGreenhill** [comment]
Given that their nexus file is the direct input that generated the trees, I think we should grab theirs (it also simplifies the phlorest code too). Agree? 

( '-' vs '?' is generally treated the same in phylogenetic programs, especially for binary data. Our missing is technically more semantically correct for linguistic data)

**Comment by xrotwang** [comment]
ok, then I'll try to re-order `etc/characters.csv` accordingly.
